apiVersion: apps/v1
kind: Deployment
metadata:
  name: deck-curator-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deck-curator-testing
  template:
    metadata:
      labels:
        app: deck-curator-testing
    spec:
      containers:
      - name: deck-curator
        image: oci.smeago.com:5000/test-deck-curator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 101
          runAsGroup: 101
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5